      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: java-hello-world
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: java-hello-world
        template:
          metadata:
            labels:
              app: java-hello-world
          spec:
            containers:
             - name: java-hello-world
               image: bhavyascaler/java-hello-world:latest
               command: ["sh", "-c", "java -jar /app/app.jar; sleep 3600"]
            restartPolicy: Always
